// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuu3dgMr5n_phDFF2VgaK3FArrCgFBfkY',
    appId: '1:304648794531:web:d0d6378b539064e6246a16',
    messagingSenderId: '304648794531',
    projectId: 'my-database-a37bc',
    authDomain: 'my-database-a37bc.firebaseapp.com',
    storageBucket: 'my-database-a37bc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0XDhtuUE4Ro8apJwE8aarkCGsBZLotVg',
    appId: '1:304648794531:android:66bd81a9b2894c0f246a16',
    messagingSenderId: '304648794531',
    projectId: 'my-database-a37bc',
    storageBucket: 'my-database-a37bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLcOnBL64I8kT45lEvE5F8WLiLI2B6vdM',
    appId: '1:304648794531:ios:0dffe1f706d5ce8f246a16',
    messagingSenderId: '304648794531',
    projectId: 'my-database-a37bc',
    storageBucket: 'my-database-a37bc.appspot.com',
    iosBundleId: 'com.example.realEstateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLcOnBL64I8kT45lEvE5F8WLiLI2B6vdM',
    appId: '1:304648794531:ios:0dffe1f706d5ce8f246a16',
    messagingSenderId: '304648794531',
    projectId: 'my-database-a37bc',
    storageBucket: 'my-database-a37bc.appspot.com',
    iosBundleId: 'com.example.realEstateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuu3dgMr5n_phDFF2VgaK3FArrCgFBfkY',
    appId: '1:304648794531:web:0f4a6b8f4ecd79ce246a16',
    messagingSenderId: '304648794531',
    projectId: 'my-database-a37bc',
    authDomain: 'my-database-a37bc.firebaseapp.com',
    storageBucket: 'my-database-a37bc.appspot.com',
  );
}
